# Generated by Django 4.1.7 on 2023-02-23 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0004_aboutme"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aboutme",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="blogpost",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
