# Generated by Django 4.1.6 on 2023-02-14 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="thumbnail",
            field=models.ImageField(blank=True, upload_to="photos/project"),
        ),
    ]
