# Generated by Django 4.1.6 on 2023-02-15 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0002_project_thumbnail"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="skills",
            field=models.CharField(default="", max_length=2000),
            preserve_default=False,
        ),
    ]
