# Generated by Django 3.1.7 on 2023-02-22 23:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_project_skills'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description du projet'),
        ),
        migrations.AlterField(
            model_name='project',
            name='field',
            field=models.CharField(choices=[('ML', 'Machine Learning'), ('DL', 'Deep Learning'), ('DS', 'Data Science'), ('DA', 'Data Analysis'), ('DE', 'Data Engineering')], max_length=5),
        ),
        migrations.AlterField(
            model_name='project',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='project',
            name='skills',
            field=models.TextField(blank=True, verbose_name='Compétences cibles'),
        ),
        migrations.AlterField(
            model_name='project',
            name='summary',
            field=models.TextField(blank=True, verbose_name='Résumé du projet'),
        ),
        migrations.AlterField(
            model_name='project',
            name='year_created',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(2000), django.core.validators.MaxValueValidator(2025)]),
        ),
    ]
